# Default values for redpanda-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# nameOverride -- Override name of app
nameOverride: ""

# fullnameOverride -- Override the fully qualified app name
fullnameOverride: ""

# replicaCount -- Number of instances of Redpanda Operator
replicaCount: 1

# Kubernetes Cluster Domain
clusterDomain: cluster.local

image:
  # image.repository -- Repository that Redpanda Operator image is available
  repository: vectorized/redpanda-operator
  # image.tag -- Define the Redpanda Operator container tag
  tag: |-
    {{ .Chart.AppVersion }}
  # image.pullPolicy -- Define the pullPolicy for Redpanda Operator image
  pullPolicy: IfNotPresent

configurator:
  # configurator.repository -- Repository that Redpanda configurator image is available
  repository: vectorized/configurator
  # configurator.tag -- Define the Redpanda configurator container tag
  tag: |-
    {{ .Chart.AppVersion }}
  # configurator.pullPolicy -- Define the pullPolicy for Redpanda configurator image
  pullPolicy: IfNotPresent

config:
  apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
  kind: ControllerManagerConfig
  health:
    healthProbeBindAddress: :8081
  metrics:
    bindAddress: 127.0.0.1:8080
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceName: aa9fc693.vectorized.io

# imagePullSecrets -- Redpanda Operator container registry pullSecret (ex: specify docker registry credentials)
imagePullSecrets: []

# logLevel -- Set Redpanda Operator log level (debug, info, error, panic, fatal)
logLevel: "info"

rbac:
  # rbac.create -- Specifies whether the RBAC resources should be created
  create: true

webhook:
  # webhook.create -- Specifies whether the Webhook resources should configured
  enabled: true

serviceAccount:
  # serviceAccount.create -- Specifies whether a service account should be created
  create: true
  # serviceAccount.name -- The name of the service account to use. If not set name is generated using the fullname template
  name:

# resources -- Set resources requests/limits for Redpanda Operator PODs
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  limits:
#   cpu: 100m
#   memory: 30Mi
#  requests:
#   cpu: 100m
#   memory: 20Mi

# nodeSelector -- Allows to schedule Redpanda Operator on specific nodes
nodeSelector: {}
# tolerations -- Allows to schedule Redpanda Operator on tainted nodes
tolerations: []
# affinity -- Allows to specify affinity for Redpanda Operator PODs
affinity: {}

# podAnnotations -- Allows setting additional annotations for Redpanda Operator PODs
podAnnotations: {}
# podLabels -- Allows setting additional labels for for Redpanda Operator PODs
podLabels: {}

# labels -- Allows to assign labels to the resources created by this helm chart
labels:

# monitoring -- Add service monitor to the deployment
monitoring:
  enabled: false

webhookSecretName: webhook-server-cert

# scope -- change the scope and therefore the resource the controller will manage
# only "Cluster" and "Namespace" supported
scope: Namespace
