blank_issues_enabled: true
contact_links:
  - name: ğŸ‘‹ Slack
    url: https://vectorized.io/slack
    about: Chat and ask questions in real time!
  - name: â“ Github Discussions
    url: https://github.com/redpanda-data/redpanda/discussions
    about: For longer, async, thoughtful discussions
  - name: ğŸ’­ Product Feedback
    url: https://vectorized.io/feedback/
    about: Let us know how we can improve your experience


