apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-sample-sasl
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 1
  enableSasl: true
  superUsers:
    - admin
  resources:
    requests:
      cpu: 1
      memory: 1.2G
    limits:
      cpu: 1
      memory: 1.2G
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
     - port: 9092
    pandaproxyApi:
     - port: 8082
    adminApi:
    - port: 9644
    developerMode: true
