{{/*
Copyright 2020 Redpanda Data, Inc.

Use of this software is governed by the Business Source License
included in the file licenses/BSL.md

As of the Change Date specified in that file, in accordance with
the Business Source License, use of this software will be governed
by the Apache License, Version 2.0
*/}}

{{- if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-serving-cert
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
spec:
  dnsNames:
    - {{ include "redpanda-operator.name" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "redpanda-operator.name" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
  issuerRef:
    kind: Issuer
    name: {{ include "redpanda-operator.fullname" . }}-selfsigned-issuer
  secretName: {{ include "redpanda-operator.webhook-cert" . }}
  privateKey:
    rotationPolicy: Never
{{- end }}
