{{/*
Copyright 2020 Redpanda Data, Inc.

Use of this software is governed by the Business Source License
included in the file licenses/BSL.md

As of the Change Date specified in that file, in accordance with
the Business Source License, use of this software will be governed
by the Apache License, Version 2.0
*/}}

{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redpanda-operator.fullname" . }}-proxy-role
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redpanda-operator.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ template "redpanda-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
