{{/*
Copyright 2020 Redpanda Data, Inc.

Use of this software is governed by the Business Source License
included in the file licenses/BSL.md

As of the Change Date specified in that file, in accordance with
the Business Source License, use of this software will be governed
by the Apache License, Version 2.0
*/}}

{{- if .Values.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "redpanda-operator.fullname" . }}-election-rolebinding
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "redpanda-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "redpanda-operator.fullname" . }}-election-role
  apiGroup: rbac.authorization.k8s.io
  {{- if eq .Values.scope "Namespace" }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "redpanda-operator.fullname" . }}
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "redpanda-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "redpanda-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end -}}
