kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: vectorizedcloud/kindestnode:v1.21.1-pr2515
- role: worker
  image: vectorizedcloud/kindestnode:v1.21.1-pr2515
- role: worker
  image: vectorizedcloud/kindestnode:v1.21.1-pr2515
- role: worker
  image: vectorizedcloud/kindestnode:v1.21.1-pr2515
- role: worker
  image: vectorizedcloud/kindestnode:v1.21.1-pr2515
