apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContainers:
  - vectorized/redpanda-operator:latest
  - vectorized/configurator:latest
testDirs:
  - ./tests/e2e-helm
kindConfig: ./kind.yaml
kindNodeCache: false
commands:
  - command: "./hack/install-cert-manager.sh"
  - command: "kubectl apply -k ./config/crd"
  - command: "kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml"
  - command: "helm dep up ./helm-chart/charts/redpanda-operator"
  - command: "helm install --set configurator.tag=latest --set image.tag=latest --namespace helm-test --create-namespace redpanda-operator ./helm-chart/charts/redpanda-operator"
  - command: "./hack/wait-for-webhook-ready.sh"
artifactsDir: tests/_helm_e2e_artifacts
timeout: 300
reportFormat: xml
parallel: 3
