apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContainers:
  - vectorized/redpanda-operator:dev
  - vectorized/configurator:dev
testDirs:
  - ./tests/e2e
kindConfig: ./kind.yaml
kindNodeCache: false
commands:
  - command: "kubectl taint nodes -l node-role.kubernetes.io/master= node-role.kubernetes.io/master:NoSchedule-"
  - command: "./hack/install-cert-manager.sh"
  - command: "kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/e23ff77fceba6a5d9f190f5d1a123c87701dc964/bundle.yaml"
  - command: "make deploy"
  - command: "./hack/wait-for-webhook-ready.sh"
  - command: "mkdir -p tests/_e2e_artifacts"
artifactsDir: tests/_e2e_artifacts
timeout: 300
reportFormat: xml
parallel: 1
