---
name: BK slash-command
on:
  repository_dispatch:
    types:
      - cdt-command
      - ci-repeat-command
      - dt-command
      - microbench-command
      - publish-to-install-pack-command
      - rp-unit-test-command
      - test-arm64-command
      - test-codecov-command
      - test-rc-pipeline-command
      - test-release-pipeline-command
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SM_READONLY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SM_READONLY_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: get secrets from aws sm
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
            ,sdlc/prod/github/buildkite_token
          parse-json-secrets: true
      - uses: actions/checkout@v4
        with:
          repository: redpanda-data/sparse-checkout
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          path: sparse-checkout
      - uses: ./sparse-checkout
        with:
          repository: redpanda-data/vtools
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          patterns: actions
          path: ghca
      - name: Buildkite slash command action
        uses: ./ghca/actions/buildkite-slash-commands
        with:
          buildkite_token: ${{ env.BUILDKITE_TOKEN }}
          buildkite_org: redpanda
          buildkite_pipeline: redpanda
          command: ${{ github.event.client_payload.slash_command.command }}
      - name: Success reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
      - name: Error response
        if: failure()
        uses: ./ghca/actions/slash-command-error
        with:
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          body: ${{ env.ERROR_MSG }}
