---
name: Add comment to JIRA Issue
on:
  issue_comment:
    types: [created]
jobs:
  add_jira_comment:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: install dependencies
        env:
          SCRIPT_DIR: ${{ github.workspace }}/.github/workflows/scripts
        run: pip install -r ${SCRIPT_DIR}/requirements.txt
      - name: install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SM_READONLY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SM_READONLY_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: get secrets from aws sm
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/jira
          parse-json-secrets: true
      - name: Add comment to JIRA Issue
        env:
          SCRIPT_DIR: ${{ github.workspace }}/.github/workflows/scripts
          JIRA_TOKEN: ${{ env.JIRA_TOKEN  }}
          JIRA_USER: ${{ env.JIRA_USER  }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_COMMENT: ${{ github.event.comment.body }}
        run: python ${SCRIPT_DIR}/jira_helper.py UPDATE_COMMENT --verbose -p CORE
