# Copyright 2021 Vectorized, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: helm chart release
on:
  release:
    types: [published]

jobs:
  helm-release:
    runs-on: ubuntu-20.04
    container: quay.io/helmpack/chart-releaser:v1.2.0
    steps:

    - name: Install Git
      run: apk update && apk upgrade && apk add --no-cache git

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.1

    - name: Package helm chart
      working-directory: src/go/k8s/helm-chart/charts
      run: helm package -u --version ${{ github.event.release.tag_name }} --app-version ${{ github.event.release.tag_name }} redpanda-operator

    - name: Upload helm package to release
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src/go/k8s/helm-chart/charts/redpanda-operator-${{ github.event.release.tag_name }}.tgz
        asset_name: redpanda-operator-${{ github.event.release.tag_name }}.tgz
        tag: ${{ github.event.release.tag_name }}

    - name: Update index
      if: contains(github.event.release.tag_name, '-beta') == false
      run: |
        cr index -o vectorizedio -r redpanda -c https://charts.vectorized.io/ -i index.yaml -p src/go/k8s/helm-chart/charts -t ${{ secrets.GITHUB_TOKEN }} --push --release-name-template "{{ .Version }}"
