# Copyright 2020 Redpanda Data, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: Homebrew
on:
  release:
    types: [published]

jobs:
  update-homebrew:
    name: Update Homebrew
    runs-on: ubuntu-latest
    steps:
    - name: Update the amd64 homebrew tap
      uses: mislav/bump-homebrew-formula-action@v2
      with:
        formula-name: redpanda
        homebrew-tap: ${{ github.repository_owner }}/homebrew-tap
        download-url: https://github.com/redpanda-data/redpanda/releases/download/${{ github.ref_name }}/rpk-darwin-amd64.zip
      env:
        COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_COMMITTER_TOKEN }}
