# Copyright 2020 Vectorized, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: Homebrew
on:
  release:
    types: [published]

jobs:
  update-homebrew:
    name: Update Homebrew
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Update the amd64 homebrew tap
      if: contains(steps.get_version.outputs.VERSION, '-beta') == false
      uses: mislav/bump-homebrew-formula-action@v1.8
      with:
        formula-name: redpanda
        homebrew-tap: vectorizedio/homebrew-tap
        base-branch: main
        download-url: https://github.com/vectorizedio/redpanda/releases/download/${{ steps.get_version.outputs.VERSION }}/rpk-darwin-amd64.zip
      env:
        COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}

    - name: Update the arm64 homebrew tap
      if: contains(steps.get_version.outputs.VERSION, '-beta') == false
      uses: mislav/bump-homebrew-formula-action@v1.8
      with:
        formula-name: redpanda
        homebrew-tap: vectorizedio/homebrew-tap
        base-branch: main
        download-url: https://github.com/vectorizedio/redpanda/releases/download/${{ steps.get_version.outputs.VERSION }}/rpk-darwin-arm64.zip
      env:
        COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
