name: Lint sh

on:
  push:
    branches:
      - 'dev'
    paths:
      - '**.sh'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - '**.sh'

jobs:
  sh:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install shfmt
      env:
        SHFMT_VER: 3.6.0
      run: |
        mkdir -v -p "$HOME/.local/bin"
        wget -O "$HOME/.local/bin/shfmt" "https://github.com/mvdan/sh/releases/download/v${SHFMT_VER}/shfmt_v${SHFMT_VER}_linux_amd64"
        chmod 0700 "$HOME/.local/bin/shfmt"

    - name: Run shfmt
      run: shfmt -i 2 -ci -s -d .
