# Copyright 2020 Redpanda Data, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: wasm-api
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: publish wasm-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.21.2'
          registry-url: 'https://registry.npmjs.org'

      - name: Check out code
        uses: actions/checkout@v2

      - name: publish
        run: |
          npm install
          VERSION=$(echo ${{ github.ref }} | sed 's/.*v//')
          npm run publish:wasm-api $VERSION
        working-directory: src/js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
